### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/DDIEM#1]
Hello,

Would it be possible to refactor the repository and have a "data" folder in which the actual data (RDF, CSV) can be downloaded, and another folder for the website?

Also, could the README be expanded to include more information on ddiem, including a link to the website? @aliraza995 @Marwaabdelhakim

**Comment by aliraza995** [comment]
I have refactored the code to have a website and data folder and also added information about ddiem and a link to the website.
