### ISSUE TITLE
Lost information with import into web interface

### ISSUE THREAD

**Issue by euniceyi** [bio-ontology-research-group/DDIEM#10]
Some information from the spreadsheet seems to have been lost with import into the web interface. Specifically:

- Drugs with ATC codes (instead of DB codes) are not listed in the interface by name; all of the corresponding information is present, but where the name should be is just a blank.

- When some combination therapies in the spreadsheet have a drug with "NA" as an ID (e.g., a row has [low protein diet + riboflavin + carnitine] as a combination therapy, and low protein diet is ID'd as "NA"), one NA designation sometimes results in some/all of the other drugs being disregarded, so that not all of the drugs are imported into the interface in that combination therapy. 

Please advise if these issues can be resolved computationally or if the original spreadsheet should be modified in some way.

**Comment by aliraza995** [comment]
Fixed the issues. Thanks for reporting it
