### ISSUE TITLE
SPARQL endpoint reload does not load CSS

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/DDIEM#3]
When directly going to http://ddiem.phenomebrowser.net/sparql, or after reloading (Ctrl-R) on the site, the layout changes to the default Virtuoso endpoint site.

**Comment by aliraza995** [comment]
Aah that issue is fixed not it was actually conflicting with redirecting to ontolinator for ddiem resource link resolving to describe query and ddiem sparql editor. I have changed the url for sparql page to http://ddiem.phenomebrowser.net/isparql so that they dont conflict.
