### ISSUE TITLE
Add a VOID file to the dataset

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/DDIEM#4]
It would be great to add a VOID file (https://www.w3.org/TR/void/) to the RDF data and make it available for download on the SPARQL page.

**Comment by aliraza995** [comment]
Sorry I was busy with aberowl for last few days. I will work finish it up today.

**Comment by aliraza995** [comment]
Added void triples explaining the dataset including name, description, contributors, authors, license, sparqlendpoint, website, git repository page and file format available
