### ISSUE TITLE
Classes without IDs

### ISSUE THREAD

**Issue by euniceyi** [bio-ontology-research-group/DDIEM#9]
Seven of the classes appear not to have ID numbers when viewed in Protege:

- combination therapeutic procedure
- metabolic disease therapeutic procedure
- activity modification of a genetically defective protein by epigenetic manipulation
- activity modification of a genetically defective protein by genome editing
- activity modification of a genetically defective protein by transcriptional or translational modification
- direct complementation of a genetically defective protein
- procedure to mitigate dominant effects of a genetically abnormal protein

The other 14 terms do have IDs. Please advise how and if we can assign IDs to the above terms.

**Comment by aliraza995** [comment]
@euniceyi We can assign these classes IDs, the way we have assigned IDs to other classes with DDIEM_00000[sequence number]. I think I will go ahead and update the ontology and will share on the DDIEM channel.
